#!/bin/bash
# Script for quickly setting up nodes for cluster suite testing

TMPL_NAME=tmpl_cent5-64-0
TMPL_DISKIMG=/root/images/$TMPL_NAME.img
TMPL_DISKSIZE=30
TMPL_MEM=512
TMPL_ISO_LOC=http://192.168.122.1/disk
TMPL_KS_DEV=eth0
TMPL_KS_IP=192.168.122.48
TMPL_KS_NM=255.255.255.0
TMPL_KS_CFG=http://192.168.122.1/tmpl_ks.cfg

function usage(){
    echo "You fucked up. Start over"
}


function get_template_response(){
    echo "This will wipe out any previously created template."
    read -p "Should I proceed? [y/n] " yn
    case $yn in
        [Yy]*) 
            mkclean
            mktemplate
            break;;
        [Nn]*) 
            exit;;
        *) 
            echo "That makes no sense"
            exit;;
    esac
}

function mktemplate(){
    echo "Creating template"

    virt-install --accelerate --hvm --name $TMPL_NAME \
    --connect qemu:///system --ram=$TMPL_MEM --disk path=$TMPL_DISKIMG,size=$TMPL_DISKSIZE \
    --network network:default --vnc -l $TMPL_ISO_LOC \
    --extra-args="ks=$TMPL_KS_CFG ksdevice=$TMPL_KS_DEV ip=$TMPL_KS_IP netmask=$TMPL_KS_NM"

}

function mknode(){
    echo "booberry"
}

function mkclean(){
    virsh destroy $TMPL_NAME
    virsh undefine $TMPL_NAME
    rm -rf $TMPL_DISKIMAGE
}

# script requires an argument
if [ -z "$@" ]; then
  echo "Script requires an argument"
  usage
fi

# parse args
while getopts ":tn:c" arg; do
  case $arg in
    t)
      echo "Create new template" >&2
      get_template_response
      ;;
    n)
      echo "Create new node" >&2
      mknode
      ;;
    c)
      echo "Cleaning up" >&2
      mkclean
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      usage
      exit 1
      ;;
    *)
      echo "You got me pal." >&2
      usage
      exit 1
      ;;
  esac
done
