#!/bin/bash
# Script for quickly setting up nodes for cluster suite testing
TMPL_NAME=tmpl_cent5-64-0
TMPL_LV=/dev/mapper/VolGroup00-tmpl_lv
TMPL_MEM=512
TMPL_ISO_LOC=http://192.168.122.1/disk
TMPL_KS_DEV=eth0
TMPL_KS_IP=192.168.122.48
TMPL_KS_NM=255.255.255.0
TMPL_KS_GW=192.168.122.1
TMPL_KS_CFG=http://192.168.122.1/tmpl_ks.cfg
VG_PATH=/dev/VolGroup00

function usage(){
    echo "You fucked up. Start over"
}

function mktemplate(){
    echo "This will wipe out any previously created template."

    get_response
    mkclean

    virt-install --accelerate --hvm --name $TMPL_NAME \
    --connect qemu:///system --ram=$TMPL_MEM --disk path=$TMPL_LV \
    --network network:default --vnc -l $TMPL_ISO_LOC \
    --extra-args="ks=$TMPL_KS_CFG ksdevice=$TMPL_KS_DEV ip=$TMPL_KS_IP netmask=$TMPL_KS_NM gateway=$TMPL_KS_GW"

}

function get_response(){
    read -p "Should I proceed? [y/n] " yn
    case $yn in
        [Yy]*) 
            return;;
        [Nn]*) 
            exit;;
        *) 
            echo "That makes no sense"
            exit;;
    esac
}

function mknodes(){
    echo "This will destroy any currently existing nodes"
    get_response
    for i in $(seq 3) 
      do
	if [ -e $VG_PATH/node$i ]
	  then
           lvremove -f $VG_PATH/node$i
        fi
        lvcreate --snapshot --size 1G --name node$i $VG_PATH/tmpl_lv
      done
}

function mkclean(){
    virsh destroy $TMPL_NAME
    virsh undefine $TMPL_NAME
    rm -rf $TMPL_DISKIMAGE
}

# script requires an argument
if [ -z "$@" ]; then
  echo "Script requires an argument"
  usage
fi

# parse args
while getopts ":tnc" arg; do
  case $arg in
    t)
      mktemplate
      ;;
    n)
      mknodes
      ;;
    c)
      mkclean
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      usage
      exit 1
      ;;
    *)
      echo "You got me pal." >&2
      usage
      exit 1
      ;;
  esac
done
